version: "3.9"

services:
  nginx:
    image: local/my-custom-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/static-content:/usr/share/nginx/html:ro
    ports:
      - "6680:80"
    links:
      - app

  app:
    build: .
    volumes:
      - ./web:/app:ro
      #- ./config:/usr/local/etc/php
    ports:
      - "9000:9000"
    working_dir: /app
