version: "3.9"

services:
  nginx:
    image: local/my-custom-nginx
    volumes:
      - ./nginx:/etc/nginx/nginx.conf:ro
      - ./nginx/static-content:/usr/share/nginx/html:ro
    ports:
      - "6680:80"


  php-fpm:
    image: php:7.4-fpm

